server:
  port: 8000

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema:
          registry:
            url: http://localhost:8081